### PR TITLE
Added fabric-permissions-api (https://github.com/lucko/fabric-permissions-api) [luckperms] support

### PR DESCRIPTION
**Pull request by Nidre**
https://github.com/CodedSakura/FabricTPA/issues/7

### CODE REVIEW

**Comment by Nidre** [comment]
One problem, it's now require fabric-api-prermission, i think it can be optional, but i don't know how do it.

**Comment by CodedSakura** [comment]
> One problem, it's now require fabric-api-prermission, i think it can be optional, but i don't know how do it.

Yea, would be much better if it was an optional dependency, will merge if that's fixed

**Comment by Nidre** [comment]
At the moment I really have no idea how to do this without breaking the "one-class" structure.

**Comment by Nidre** [comment]
Simple variant is just include it in mod.

**Comment by CodedSakura** [comment]
I don't mind if it's split up into multiple classes, I'm planning on rewriting it entirely anyway, since it was my 1st mod.

I think I'd separate the command registration segment (since it's the part that needs FPAPI) and pass the runnable methods as parameters to the generators, depending on whether FPAPI is installed or not.

**Comment by spaceclouds42** [comment]
> i think it can be optional, but i don't know how do it.

https://github.com/PotatoPresident/InvView/blob/2a411f44ac24ddf5d0beb64c6ced80aa25b5f7ba/src/main/java/us/potatoboy/invview/InvView.java#L30

**Comment by CodedSakura** [comment]
turns out it's optional by default, added it in 2.0.0

**Pull request closed without merging**
